# -*- coding: utf-8 -*-
"""NLP_Proje_Kodları.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PCVCao04VgKHJMApYb3VIMf_AhbH7ZpZ

2. Hafta – Veri Hazırlama + Önişleme
"""

import pandas as pd
import numpy as np
import re
import seaborn as sns
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

# 1. VERİYİ YÜKLE
df = pd.read_csv("nlp_proje_verisi.csv", encoding='utf-8')
print(f"Toplam Veri Sayısı: {len(df)}")

# 2. VERİ TEMİZLEME ADIMLARI
# Yorum sütunu boş olan satırları siler
df = df.dropna(subset=['Yorum', 'Puan'])

# b. Tekrarlayan Veri Kontrolü (Duplicate temizliği)
# Aynı yorumdan birden fazla varsa siler (Sadece 1 tanesini tutar)
df = df.drop_duplicates(subset=['Yorum'])

print(f"Temizlik Sonrası Veri Sayısı: {len(df)}")

# 3. ETİKET DÖNÜŞÜMÜ (Label Mapping)
# Hedefimiz: 1-5 Puanı -> Negatif/Nötr/Pozitif'e çevirmek.
# 1-2 Puan -> Negatif (0)
# 3 Puan   -> Nötr (1)
# 4-5 Puan -> Pozitif (2)

def skor_donustur(puan):
    if puan <= 2:
        return 0 # Negatif
    elif puan == 3:
        return 1 # Nötr
    else:
        return 2 # Pozitif

df['Duygu_Sinifi'] = df['Puan'].apply(skor_donustur)

# 4. ÖN İŞLEME ADIMLARI (Preprocessing)
def metin_temizle(text):
    # a. Küçük harfe çevir (Lowercase)
    text = text.lower()

    # b. Gereksiz boşlukları sil
    text = text.strip()

    # c. Özel karakterleri ve noktalama işaretlerini temizle
    # Sadece Türkçe harfler ve boşluk kalsın
    text = text.translate(str.maketrans('', '', string.punctuation))

    # d. Fazla boşlukları teke indir
    text = re.sub(r'\s+', ' ', text)

    return text

# Temizlik fonksiyonunu uygula
df['Temiz_Yorum'] = df['Yorum'].apply(metin_temizle)

# 5. İSTATİSTİKLER VE GÖRSELLEŞTİRME
print("-" * 30)
print("Sınıf Dağılımı:")
print(df['Duygu_Sinifi'].value_counts())

# Grafik Çiz
plt.figure(figsize=(8,5))
sns.countplot(x='Duygu_Sinifi', data=df, palette='viridis')
plt.title('Duygu Sınıflarının Dağılımı (0: Negatif, 1: Nötr, 2: Pozitif)')
plt.xlabel('Duygu Sınıfı')
plt.ylabel('Yorum Sayısı')
plt.savefig('sinif_dagilimi.png') # Resmi kaydeder
plt.show()

# 6. EĞİTİM - TEST AYRIMI (Train-Test Split)
# Veriyi %80 Eğitim (Train), %10 Test (Test), %10 Doğrulama (Validation) olarak bölme.

X = df['Temiz_Yorum']
y = df['Duygu_Sinifi']

# Önce %80 Train, %20 Temp (Test+Val)
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Sonra Temp'i ikiye böl (%10 Test, %10 Val)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

print("-" * 30)
print(f"Eğitim Seti: {len(X_train)} satır")
print(f"Doğrulama Seti: {len(X_val)} satır")
print(f"Test Seti: {len(X_test)} satır")

# 7. KAYDETME
# DataFrame'e çevirip kaydedelim
train_df = pd.DataFrame({'text': X_train, 'label': y_train})
val_df = pd.DataFrame({'text': X_val, 'label': y_val})
test_df = pd.DataFrame({'text': X_test, 'label': y_test})

train_df.to_csv("train.csv", index=False, encoding='utf-8-sig')
val_df.to_csv("validation.csv", index=False, encoding='utf-8-sig')
test_df.to_csv("test.csv", index=False, encoding='utf-8-sig')

print("✅ Dosyalar başarıyla oluşturuldu: train.csv, validation.csv, test.csv")

"""3. Hafta – Modelleme"""

# 1. Kurulumlar ve Kütüphaneler
!pip install transformers datasets evaluate scikit-learn seaborn matplotlib
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
from datasets import load_dataset, DatasetDict

# GPU Kontrolü
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Kullanılan Cihaz: {device} (Eğer 'cpu' yazıyorsa eğitim çok yavaş olur!)")

# 2. VERİ YÜKLEME
train_df = pd.read_csv("train.csv")
val_df = pd.read_csv("validation.csv")
test_df = pd.read_csv("test.csv")

print(f"Eğitim Verisi: {len(train_df)}")
print(f"Test Verisi: {len(test_df)}")

# 3. BASELINE MODEL (Referans Modeli: TF-IDF + Logistic Regression)
print("\n--- 1. MODEL: GELENEKSEL YÖNTEM (TF-IDF + LR) ---")

# Kelimeleri sayıya çevir (Embedding: TF-IDF)
vectorizer = TfidfVectorizer(max_features=5000)
X_train_tfidf = vectorizer.fit_transform(train_df['text'].astype(str))
X_test_tfidf = vectorizer.transform(test_df['text'].astype(str))

# Modeli eğit
lr_model = LogisticRegression(max_iter=1000)
lr_model.fit(X_train_tfidf, train_df['label'])

# Tahmin yap
lr_preds = lr_model.predict(X_test_tfidf)
lr_acc = accuracy_score(test_df['label'], lr_preds)

print(f"Geleneksel Model Başarısı (Accuracy): %{lr_acc*100:.2f}")
print("Sınıflandırma Raporu:\n", classification_report(test_df['label'], lr_preds))

# 4. ANA MODEL: BERT (Deep Learning)
print("\n--- 2. MODEL: MODERN YÖNTEM (BERTurk) ---")

model_name = "dbmdz/bert-base-turkish-cased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

# Veriyi HuggingFace formatına çevir
dataset = DatasetDict({
    "train": load_dataset("csv", data_files="train.csv")['train'],
    "validation": load_dataset("csv", data_files="validation.csv")['train'],
    "test": load_dataset("csv", data_files="test.csv")['train']
})
# Tokenize Fonksiyonu
def preprocess_function(examples):
    return tokenizer(examples["text"], truncation=True, padding="max_length", max_length=128)

tokenized_datasets = dataset.map(preprocess_function, batched=True)

# Modeli Yükle (3 Sınıf: 0, 1, 2)
model = AutoModelForSequenceClassification.from_pretrained(model_name, num_labels=3)
model.to(device)

# Eğitim Ayarları (Hyperparameters)
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch", # Her epoch sonunda test et
    save_strategy="epoch",
    learning_rate=2e-5,          # Çok küçük adımlarla öğren
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,          # Veri setini 3 kere dön
    weight_decay=0.01,
    load_best_model_at_end=True,
    logging_dir='./logs',
)

# Metrik Fonksiyonu
import evaluate
metric = evaluate.load("accuracy")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

# Trainer Başlat
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    compute_metrics=compute_metrics,
)
# Eğitimi Başlat
print("BERT Eğitimi Başlıyor...")
trainer.train()

# 5. SONUÇLAR
# Test seti üzerinde tahmin al
predictions = trainer.predict(tokenized_datasets["test"])
bert_preds = np.argmax(predictions.predictions, axis=-1)
bert_acc = accuracy_score(test_df['label'], bert_preds)

print(f"\nBERT Model Başarısı: %{bert_acc*100:.2f}")

# Karşılaştırma Grafiği

import matplotlib.pyplot as plt
import seaborn as sns

# Grafik Stili (Daha temiz bir görünüm için)
sns.set_style("whitegrid")

# Veriler (Hafızadaki değişkenler için kullanılır)
methods = ['Geleneksel\n(TF-IDF + LR)', 'Modern\n(BERTurk)']
scores = [lr_acc, bert_acc]

# Renk Paleti (Soft Gri ve Kurumsal Mavi)
colors = ['#95a5a6', '#3498db']

plt.figure(figsize=(8, 6))
bars = plt.bar(methods, scores, color=colors, width=0.6)

# Ekseni Daraltma
plt.ylim(0.80, 1.01)

plt.title('Model Başarı Karşılaştırması (Accuracy)', fontsize=14, fontweight='bold')
plt.ylabel('Başarı Oranı', fontsize=12)

# Sütunların üzerine sayıları yazma
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2., height + 0.005,
             f'%{height*100:.2f}',
             ha='center', va='bottom', fontsize=12, fontweight='bold', color='black')

# Kenar çizgilerini kaldırma
sns.despine(left=True, bottom=True)

plt.tight_layout()
plt.savefig("karsilastirma_grafigi.png", dpi=300)
plt.show()

# BERT Confusion Matrix
cm = confusion_matrix(test_df['label'], bert_preds)
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=['Negatif','Nötr','Pozitif'], yticklabels=['Negatif','Nötr','Pozitif'])
plt.title('BERT Confusion Matrix')
plt.ylabel('Gerçek')
plt.xlabel('Tahmin')
plt.savefig("bert_confusion_matrix.png")
plt.show()

# 6. Modeli Kaydet
model.save_pretrained("my_sentiment_model")
tokenizer.save_pretrained("my_sentiment_model")
print("Model 'my_sentiment_model' klasörüne kaydedildi.")